services:
    greeter.simple:
        class: App\Greeter\SimpleGreeter
    greeter.controller:
        class: App\Controller\GreeterController
        arguments:
            - "@greeter.simple"
    published_message.listener:
        class: App\EventListener\PublishedMessageExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
